# =============================
# Passive Radar configuration
# =============================

# Режим работы
mode: udp         # варианты: udp | file

# ===== UDP Source =====
udp:
  host: 0.0.0.0    # адрес для приёма (0.0.0.0 = все интерфейсы)
  port: 5000       # порт для приёма
  buffer_size: 8192

# ===== File Source =====
file:
  path: data/test_iq.bin   # путь к IQ файлу
  chunk_size: 4096         # количество IQ-семплов за итерацию

# ===== General =====
sample_rate: 1.0e6         # частота дискретизации (Гц)
center_freq: 650e6         # центральная частота (Гц)
